package com.microsoft.sqlserver.ReportExecution2005;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * The Reporting Services Execution Service enables report execution
 *
 * This class was generated by Apache CXF 3.0.16
 * 2018-03-10T18:18:02.717+03:00
 * Generated source version: 3.0.16
 * 
 */
@WebServiceClient(name = "ReportExecutionService", 
                  wsdlLocation = "http://localhost/ReportServer/ReportExecution2005.asmx?wsdl",
                  targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices") 
public class ReportExecutionService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", "ReportExecutionService");
    public final static QName ReportExecutionServiceSoap = new QName("http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", "ReportExecutionServiceSoap");
    public final static QName ReportExecutionServiceSoap12 = new QName("http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", "ReportExecutionServiceSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost/ReportServer/ReportExecution2005.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ReportExecutionService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost/ReportServer/ReportExecution2005.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ReportExecutionService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ReportExecutionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReportExecutionService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ReportExecutionService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ReportExecutionService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ReportExecutionService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ReportExecutionServiceSoap
     */
    @WebEndpoint(name = "ReportExecutionServiceSoap")
    public ReportExecutionServiceSoap getReportExecutionServiceSoap() {
        return super.getPort(ReportExecutionServiceSoap, ReportExecutionServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReportExecutionServiceSoap
     */
    @WebEndpoint(name = "ReportExecutionServiceSoap")
    public ReportExecutionServiceSoap getReportExecutionServiceSoap(WebServiceFeature... features) {
        return super.getPort(ReportExecutionServiceSoap, ReportExecutionServiceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns ReportExecutionServiceSoap
     */
    @WebEndpoint(name = "ReportExecutionServiceSoap12")
    public ReportExecutionServiceSoap getReportExecutionServiceSoap12() {
        return super.getPort(ReportExecutionServiceSoap12, ReportExecutionServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReportExecutionServiceSoap
     */
    @WebEndpoint(name = "ReportExecutionServiceSoap12")
    public ReportExecutionServiceSoap getReportExecutionServiceSoap12(WebServiceFeature... features) {
        return super.getPort(ReportExecutionServiceSoap12, ReportExecutionServiceSoap.class, features);
    }

}
