
package com.microsoft.sqlserver.ReportExecution2005;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2018-03-10T18:18:02.616+03:00
 * Generated source version: 3.0.16
 * 
 */
public final class ReportExecutionServiceSoap_ReportExecutionServiceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", "ReportExecutionService");

    private ReportExecutionServiceSoap_ReportExecutionServiceSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ReportExecutionService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ReportExecutionService ss = new ReportExecutionService(wsdlURL, SERVICE_NAME);
        ReportExecutionServiceSoap port = ss.getReportExecutionServiceSoap12();  
        
        {
        System.out.println("Invoking render2...");
        com.microsoft.sqlserver.ReportExecution2005.Render2 _render2_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader _render2_executionHeader = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _render2_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _render2_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.Render2Response _render2__return = port.render2(_render2_parameters, _render2_executionHeader, _render2_trustedUserHeader, _render2_serverInfoHeader);
        System.out.println("render2.result=" + _render2__return);

        System.out.println("render2._render2_serverInfoHeader=" + _render2_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking getRenderResource...");
        com.microsoft.sqlserver.ReportExecution2005.GetRenderResource _getRenderResource_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _getRenderResource_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _getRenderResource_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.GetRenderResourceResponse _getRenderResource__return = port.getRenderResource(_getRenderResource_parameters, _getRenderResource_trustedUserHeader, _getRenderResource_serverInfoHeader);
        System.out.println("getRenderResource.result=" + _getRenderResource__return);

        System.out.println("getRenderResource._getRenderResource_serverInfoHeader=" + _getRenderResource_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking setExecutionParameters2...");
        com.microsoft.sqlserver.ReportExecution2005.SetExecutionParameters2 _setExecutionParameters2_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader _setExecutionParameters2_executionHeader = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _setExecutionParameters2_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _setExecutionParameters2_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.SetExecutionParameters2Response _setExecutionParameters2__return = port.setExecutionParameters2(_setExecutionParameters2_parameters, _setExecutionParameters2_executionHeader, _setExecutionParameters2_trustedUserHeader, _setExecutionParameters2_serverInfoHeader);
        System.out.println("setExecutionParameters2.result=" + _setExecutionParameters2__return);

        System.out.println("setExecutionParameters2._setExecutionParameters2_serverInfoHeader=" + _setExecutionParameters2_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking loadDrillthroughTarget...");
        com.microsoft.sqlserver.ReportExecution2005.LoadDrillthroughTarget _loadDrillthroughTarget_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader _loadDrillthroughTarget_executionHeaderVal = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader> _loadDrillthroughTarget_executionHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader>(_loadDrillthroughTarget_executionHeaderVal);
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _loadDrillthroughTarget_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _loadDrillthroughTarget_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.LoadDrillthroughTargetResponse _loadDrillthroughTarget__return = port.loadDrillthroughTarget(_loadDrillthroughTarget_parameters, _loadDrillthroughTarget_executionHeader, _loadDrillthroughTarget_trustedUserHeader, _loadDrillthroughTarget_serverInfoHeader);
        System.out.println("loadDrillthroughTarget.result=" + _loadDrillthroughTarget__return);

        System.out.println("loadDrillthroughTarget._loadDrillthroughTarget_executionHeader=" + _loadDrillthroughTarget_executionHeader.value);
        System.out.println("loadDrillthroughTarget._loadDrillthroughTarget_serverInfoHeader=" + _loadDrillthroughTarget_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking getDocumentMap...");
        com.microsoft.sqlserver.ReportExecution2005.GetDocumentMap _getDocumentMap_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader _getDocumentMap_executionHeader = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _getDocumentMap_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _getDocumentMap_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.GetDocumentMapResponse _getDocumentMap__return = port.getDocumentMap(_getDocumentMap_parameters, _getDocumentMap_executionHeader, _getDocumentMap_trustedUserHeader, _getDocumentMap_serverInfoHeader);
        System.out.println("getDocumentMap.result=" + _getDocumentMap__return);

        System.out.println("getDocumentMap._getDocumentMap_serverInfoHeader=" + _getDocumentMap_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking listRenderingExtensions...");
        com.microsoft.sqlserver.ReportExecution2005.ListRenderingExtensions _listRenderingExtensions_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _listRenderingExtensions_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _listRenderingExtensions_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.ListRenderingExtensionsResponse _listRenderingExtensions__return = port.listRenderingExtensions(_listRenderingExtensions_parameters, _listRenderingExtensions_trustedUserHeader, _listRenderingExtensions_serverInfoHeader);
        System.out.println("listRenderingExtensions.result=" + _listRenderingExtensions__return);

        System.out.println("listRenderingExtensions._listRenderingExtensions_serverInfoHeader=" + _listRenderingExtensions_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking listSecureMethods...");
        com.microsoft.sqlserver.ReportExecution2005.ListSecureMethods _listSecureMethods_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _listSecureMethods_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _listSecureMethods_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.ListSecureMethodsResponse _listSecureMethods__return = port.listSecureMethods(_listSecureMethods_parameters, _listSecureMethods_trustedUserHeader, _listSecureMethods_serverInfoHeader);
        System.out.println("listSecureMethods.result=" + _listSecureMethods__return);

        System.out.println("listSecureMethods._listSecureMethods_serverInfoHeader=" + _listSecureMethods_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking setExecutionParameters...");
        com.microsoft.sqlserver.ReportExecution2005.SetExecutionParameters _setExecutionParameters_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader _setExecutionParameters_executionHeader = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _setExecutionParameters_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _setExecutionParameters_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.SetExecutionParametersResponse _setExecutionParameters__return = port.setExecutionParameters(_setExecutionParameters_parameters, _setExecutionParameters_executionHeader, _setExecutionParameters_trustedUserHeader, _setExecutionParameters_serverInfoHeader);
        System.out.println("setExecutionParameters.result=" + _setExecutionParameters__return);

        System.out.println("setExecutionParameters._setExecutionParameters_serverInfoHeader=" + _setExecutionParameters_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking resetExecution2...");
        com.microsoft.sqlserver.ReportExecution2005.ResetExecution2 _resetExecution2_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader _resetExecution2_executionHeader = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _resetExecution2_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _resetExecution2_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.ResetExecution2Response _resetExecution2__return = port.resetExecution2(_resetExecution2_parameters, _resetExecution2_executionHeader, _resetExecution2_trustedUserHeader, _resetExecution2_serverInfoHeader);
        System.out.println("resetExecution2.result=" + _resetExecution2__return);

        System.out.println("resetExecution2._resetExecution2_serverInfoHeader=" + _resetExecution2_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking sort2...");
        com.microsoft.sqlserver.ReportExecution2005.Sort2 _sort2_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader _sort2_executionHeader = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _sort2_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _sort2_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.Sort2Response _sort2__return = port.sort2(_sort2_parameters, _sort2_executionHeader, _sort2_trustedUserHeader, _sort2_serverInfoHeader);
        System.out.println("sort2.result=" + _sort2__return);

        System.out.println("sort2._sort2_serverInfoHeader=" + _sort2_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking navigateBookmark...");
        com.microsoft.sqlserver.ReportExecution2005.NavigateBookmark _navigateBookmark_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader _navigateBookmark_executionHeader = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _navigateBookmark_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _navigateBookmark_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.NavigateBookmarkResponse _navigateBookmark__return = port.navigateBookmark(_navigateBookmark_parameters, _navigateBookmark_executionHeader, _navigateBookmark_trustedUserHeader, _navigateBookmark_serverInfoHeader);
        System.out.println("navigateBookmark.result=" + _navigateBookmark__return);

        System.out.println("navigateBookmark._navigateBookmark_serverInfoHeader=" + _navigateBookmark_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking logoff...");
        com.microsoft.sqlserver.ReportExecution2005.Logoff _logoff_parameters = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _logoff_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.LogoffResponse _logoff__return = port.logoff(_logoff_parameters, _logoff_serverInfoHeader);
        System.out.println("logoff.result=" + _logoff__return);

        System.out.println("logoff._logoff_serverInfoHeader=" + _logoff_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking loadReport...");
        com.microsoft.sqlserver.ReportExecution2005.LoadReport _loadReport_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _loadReport_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader> _loadReport_executionHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader>();
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _loadReport_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.LoadReportResponse _loadReport__return = port.loadReport(_loadReport_parameters, _loadReport_trustedUserHeader, _loadReport_executionHeader, _loadReport_serverInfoHeader);
        System.out.println("loadReport.result=" + _loadReport__return);

        System.out.println("loadReport._loadReport_executionHeader=" + _loadReport_executionHeader.value);
        System.out.println("loadReport._loadReport_serverInfoHeader=" + _loadReport_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking loadReportDefinition...");
        com.microsoft.sqlserver.ReportExecution2005.LoadReportDefinition _loadReportDefinition_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _loadReportDefinition_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader> _loadReportDefinition_executionHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader>();
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _loadReportDefinition_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.LoadReportDefinitionResponse _loadReportDefinition__return = port.loadReportDefinition(_loadReportDefinition_parameters, _loadReportDefinition_trustedUserHeader, _loadReportDefinition_executionHeader, _loadReportDefinition_serverInfoHeader);
        System.out.println("loadReportDefinition.result=" + _loadReportDefinition__return);

        System.out.println("loadReportDefinition._loadReportDefinition_executionHeader=" + _loadReportDefinition_executionHeader.value);
        System.out.println("loadReportDefinition._loadReportDefinition_serverInfoHeader=" + _loadReportDefinition_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking loadReport2...");
        com.microsoft.sqlserver.ReportExecution2005.LoadReport2 _loadReport2_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _loadReport2_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader> _loadReport2_executionHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader>();
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _loadReport2_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.LoadReport2Response _loadReport2__return = port.loadReport2(_loadReport2_parameters, _loadReport2_trustedUserHeader, _loadReport2_executionHeader, _loadReport2_serverInfoHeader);
        System.out.println("loadReport2.result=" + _loadReport2__return);

        System.out.println("loadReport2._loadReport2_executionHeader=" + _loadReport2_executionHeader.value);
        System.out.println("loadReport2._loadReport2_serverInfoHeader=" + _loadReport2_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking loadDrillthroughTarget2...");
        com.microsoft.sqlserver.ReportExecution2005.LoadDrillthroughTarget2 _loadDrillthroughTarget2_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader _loadDrillthroughTarget2_executionHeaderVal = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader> _loadDrillthroughTarget2_executionHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader>(_loadDrillthroughTarget2_executionHeaderVal);
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _loadDrillthroughTarget2_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _loadDrillthroughTarget2_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.LoadDrillthroughTarget2Response _loadDrillthroughTarget2__return = port.loadDrillthroughTarget2(_loadDrillthroughTarget2_parameters, _loadDrillthroughTarget2_executionHeader, _loadDrillthroughTarget2_trustedUserHeader, _loadDrillthroughTarget2_serverInfoHeader);
        System.out.println("loadDrillthroughTarget2.result=" + _loadDrillthroughTarget2__return);

        System.out.println("loadDrillthroughTarget2._loadDrillthroughTarget2_executionHeader=" + _loadDrillthroughTarget2_executionHeader.value);
        System.out.println("loadDrillthroughTarget2._loadDrillthroughTarget2_serverInfoHeader=" + _loadDrillthroughTarget2_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking navigateDocumentMap...");
        com.microsoft.sqlserver.ReportExecution2005.NavigateDocumentMap _navigateDocumentMap_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader _navigateDocumentMap_executionHeader = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _navigateDocumentMap_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _navigateDocumentMap_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.NavigateDocumentMapResponse _navigateDocumentMap__return = port.navigateDocumentMap(_navigateDocumentMap_parameters, _navigateDocumentMap_executionHeader, _navigateDocumentMap_trustedUserHeader, _navigateDocumentMap_serverInfoHeader);
        System.out.println("navigateDocumentMap.result=" + _navigateDocumentMap__return);

        System.out.println("navigateDocumentMap._navigateDocumentMap_serverInfoHeader=" + _navigateDocumentMap_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking setExecutionCredentials2...");
        com.microsoft.sqlserver.ReportExecution2005.SetExecutionCredentials2 _setExecutionCredentials2_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader _setExecutionCredentials2_executionHeader = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _setExecutionCredentials2_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _setExecutionCredentials2_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.SetExecutionCredentials2Response _setExecutionCredentials2__return = port.setExecutionCredentials2(_setExecutionCredentials2_parameters, _setExecutionCredentials2_executionHeader, _setExecutionCredentials2_trustedUserHeader, _setExecutionCredentials2_serverInfoHeader);
        System.out.println("setExecutionCredentials2.result=" + _setExecutionCredentials2__return);

        System.out.println("setExecutionCredentials2._setExecutionCredentials2_serverInfoHeader=" + _setExecutionCredentials2_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking render...");
        com.microsoft.sqlserver.ReportExecution2005.Render _render_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader _render_executionHeader = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _render_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _render_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.RenderResponse _render__return = port.render(_render_parameters, _render_executionHeader, _render_trustedUserHeader, _render_serverInfoHeader);
        System.out.println("render.result=" + _render__return);

        System.out.println("render._render_serverInfoHeader=" + _render_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking getExecutionInfo...");
        com.microsoft.sqlserver.ReportExecution2005.GetExecutionInfo _getExecutionInfo_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader _getExecutionInfo_executionHeader = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _getExecutionInfo_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _getExecutionInfo_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.GetExecutionInfoResponse _getExecutionInfo__return = port.getExecutionInfo(_getExecutionInfo_parameters, _getExecutionInfo_executionHeader, _getExecutionInfo_trustedUserHeader, _getExecutionInfo_serverInfoHeader);
        System.out.println("getExecutionInfo.result=" + _getExecutionInfo__return);

        System.out.println("getExecutionInfo._getExecutionInfo_serverInfoHeader=" + _getExecutionInfo_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking findString...");
        com.microsoft.sqlserver.ReportExecution2005.FindString _findString_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader _findString_executionHeader = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _findString_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _findString_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.FindStringResponse _findString__return = port.findString(_findString_parameters, _findString_executionHeader, _findString_trustedUserHeader, _findString_serverInfoHeader);
        System.out.println("findString.result=" + _findString__return);

        System.out.println("findString._findString_serverInfoHeader=" + _findString_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking logonUser...");
        com.microsoft.sqlserver.ReportExecution2005.LogonUser _logonUser_parameters = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _logonUser_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.LogonUserResponse _logonUser__return = port.logonUser(_logonUser_parameters, _logonUser_serverInfoHeader);
        System.out.println("logonUser.result=" + _logonUser__return);

        System.out.println("logonUser._logonUser_serverInfoHeader=" + _logonUser_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking toggleItem...");
        com.microsoft.sqlserver.ReportExecution2005.ToggleItem _toggleItem_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader _toggleItem_executionHeader = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _toggleItem_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _toggleItem_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.ToggleItemResponse _toggleItem__return = port.toggleItem(_toggleItem_parameters, _toggleItem_executionHeader, _toggleItem_trustedUserHeader, _toggleItem_serverInfoHeader);
        System.out.println("toggleItem.result=" + _toggleItem__return);

        System.out.println("toggleItem._toggleItem_serverInfoHeader=" + _toggleItem_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking sort...");
        com.microsoft.sqlserver.ReportExecution2005.Sort _sort_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader _sort_executionHeader = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _sort_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _sort_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.SortResponse _sort__return = port.sort(_sort_parameters, _sort_executionHeader, _sort_trustedUserHeader, _sort_serverInfoHeader);
        System.out.println("sort.result=" + _sort__return);

        System.out.println("sort._sort_serverInfoHeader=" + _sort_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking loadReportDefinition2...");
        com.microsoft.sqlserver.ReportExecution2005.LoadReportDefinition2 _loadReportDefinition2_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _loadReportDefinition2_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader> _loadReportDefinition2_executionHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader>();
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _loadReportDefinition2_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.LoadReportDefinition2Response _loadReportDefinition2__return = port.loadReportDefinition2(_loadReportDefinition2_parameters, _loadReportDefinition2_trustedUserHeader, _loadReportDefinition2_executionHeader, _loadReportDefinition2_serverInfoHeader);
        System.out.println("loadReportDefinition2.result=" + _loadReportDefinition2__return);

        System.out.println("loadReportDefinition2._loadReportDefinition2_executionHeader=" + _loadReportDefinition2_executionHeader.value);
        System.out.println("loadReportDefinition2._loadReportDefinition2_serverInfoHeader=" + _loadReportDefinition2_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking resetExecution...");
        com.microsoft.sqlserver.ReportExecution2005.ResetExecution _resetExecution_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader _resetExecution_executionHeader = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _resetExecution_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _resetExecution_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.ResetExecutionResponse _resetExecution__return = port.resetExecution(_resetExecution_parameters, _resetExecution_executionHeader, _resetExecution_trustedUserHeader, _resetExecution_serverInfoHeader);
        System.out.println("resetExecution.result=" + _resetExecution__return);

        System.out.println("resetExecution._resetExecution_serverInfoHeader=" + _resetExecution_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking setExecutionCredentials...");
        com.microsoft.sqlserver.ReportExecution2005.SetExecutionCredentials _setExecutionCredentials_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader _setExecutionCredentials_executionHeader = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _setExecutionCredentials_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _setExecutionCredentials_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.SetExecutionCredentialsResponse _setExecutionCredentials__return = port.setExecutionCredentials(_setExecutionCredentials_parameters, _setExecutionCredentials_executionHeader, _setExecutionCredentials_trustedUserHeader, _setExecutionCredentials_serverInfoHeader);
        System.out.println("setExecutionCredentials.result=" + _setExecutionCredentials__return);

        System.out.println("setExecutionCredentials._setExecutionCredentials_serverInfoHeader=" + _setExecutionCredentials_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking getExecutionInfo2...");
        com.microsoft.sqlserver.ReportExecution2005.GetExecutionInfo2 _getExecutionInfo2_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader _getExecutionInfo2_executionHeader = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _getExecutionInfo2_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _getExecutionInfo2_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.GetExecutionInfo2Response _getExecutionInfo2__return = port.getExecutionInfo2(_getExecutionInfo2_parameters, _getExecutionInfo2_executionHeader, _getExecutionInfo2_trustedUserHeader, _getExecutionInfo2_serverInfoHeader);
        System.out.println("getExecutionInfo2.result=" + _getExecutionInfo2__return);

        System.out.println("getExecutionInfo2._getExecutionInfo2_serverInfoHeader=" + _getExecutionInfo2_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking renderStream...");
        com.microsoft.sqlserver.ReportExecution2005.RenderStream _renderStream_parameters = null;
        com.microsoft.sqlserver.ReportExecution2005.ExecutionHeader _renderStream_executionHeader = null;
        com.microsoft.sqlserver.ReportExecution2005.TrustedUserHeader _renderStream_trustedUserHeader = null;
        javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader> _renderStream_serverInfoHeader = new javax.xml.ws.Holder<com.microsoft.sqlserver.ReportExecution2005.ServerInfoHeader>();
        com.microsoft.sqlserver.ReportExecution2005.RenderStreamResponse _renderStream__return = port.renderStream(_renderStream_parameters, _renderStream_executionHeader, _renderStream_trustedUserHeader, _renderStream_serverInfoHeader);
        System.out.println("renderStream.result=" + _renderStream__return);

        System.out.println("renderStream._renderStream_serverInfoHeader=" + _renderStream_serverInfoHeader.value);

        }

        System.exit(0);
    }

}
