package com.microsoft.sqlserver.ReportExecution2005;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2018-03-10T18:18:02.658+03:00
 * Generated source version: 3.0.16
 * 
 */
@WebService(targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", name = "ReportExecutionServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ReportExecutionServiceSoap {

    @WebMethod(operationName = "Render2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Render2")
    @WebResult(name = "Render2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public Render2Response render2(
        @WebParam(partName = "parameters", name = "Render2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        Render2 parameters,
        @WebParam(partName = "ExecutionHeader", name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        ExecutionHeader executionHeader,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "GetRenderResource", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/GetRenderResource")
    @WebResult(name = "GetRenderResourceResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public GetRenderResourceResponse getRenderResource(
        @WebParam(partName = "parameters", name = "GetRenderResource", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        GetRenderResource parameters,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "SetExecutionParameters2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionParameters2")
    @WebResult(name = "SetExecutionParameters2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public SetExecutionParameters2Response setExecutionParameters2(
        @WebParam(partName = "parameters", name = "SetExecutionParameters2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        SetExecutionParameters2 parameters,
        @WebParam(partName = "ExecutionHeader", name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        ExecutionHeader executionHeader,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "LoadDrillthroughTarget", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadDrillthroughTarget")
    @WebResult(name = "LoadDrillthroughTargetResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public LoadDrillthroughTargetResponse loadDrillthroughTarget(
        @WebParam(partName = "parameters", name = "LoadDrillthroughTarget", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        LoadDrillthroughTarget parameters,
        @WebParam(partName = "ExecutionHeader", mode = WebParam.Mode.INOUT, name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ExecutionHeader> executionHeader,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "GetDocumentMap", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/GetDocumentMap")
    @WebResult(name = "GetDocumentMapResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public GetDocumentMapResponse getDocumentMap(
        @WebParam(partName = "parameters", name = "GetDocumentMap", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        GetDocumentMap parameters,
        @WebParam(partName = "ExecutionHeader", name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        ExecutionHeader executionHeader,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "ListRenderingExtensions", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ListRenderingExtensions")
    @WebResult(name = "ListRenderingExtensionsResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public ListRenderingExtensionsResponse listRenderingExtensions(
        @WebParam(partName = "parameters", name = "ListRenderingExtensions", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        ListRenderingExtensions parameters,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "ListSecureMethods", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ListSecureMethods")
    @WebResult(name = "ListSecureMethodsResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public ListSecureMethodsResponse listSecureMethods(
        @WebParam(partName = "parameters", name = "ListSecureMethods", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        ListSecureMethods parameters,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "SetExecutionParameters", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionParameters")
    @WebResult(name = "SetExecutionParametersResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public SetExecutionParametersResponse setExecutionParameters(
        @WebParam(partName = "parameters", name = "SetExecutionParameters", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        SetExecutionParameters parameters,
        @WebParam(partName = "ExecutionHeader", name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        ExecutionHeader executionHeader,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "ResetExecution2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ResetExecution2")
    @WebResult(name = "ResetExecution2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public ResetExecution2Response resetExecution2(
        @WebParam(partName = "parameters", name = "ResetExecution2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        ResetExecution2 parameters,
        @WebParam(partName = "ExecutionHeader", name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        ExecutionHeader executionHeader,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "Sort2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Sort2")
    @WebResult(name = "Sort2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public Sort2Response sort2(
        @WebParam(partName = "parameters", name = "Sort2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        Sort2 parameters,
        @WebParam(partName = "ExecutionHeader", name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        ExecutionHeader executionHeader,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "NavigateBookmark", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/NavigateBookmark")
    @WebResult(name = "NavigateBookmarkResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public NavigateBookmarkResponse navigateBookmark(
        @WebParam(partName = "parameters", name = "NavigateBookmark", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        NavigateBookmark parameters,
        @WebParam(partName = "ExecutionHeader", name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        ExecutionHeader executionHeader,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "Logoff", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Logoff")
    @WebResult(name = "LogoffResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public LogoffResponse logoff(
        @WebParam(partName = "parameters", name = "Logoff", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        Logoff parameters,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "LoadReport", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReport")
    @WebResult(name = "LoadReportResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public LoadReportResponse loadReport(
        @WebParam(partName = "parameters", name = "LoadReport", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        LoadReport parameters,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ExecutionHeader", mode = WebParam.Mode.OUT, name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ExecutionHeader> executionHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "LoadReportDefinition", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReportDefinition")
    @WebResult(name = "LoadReportDefinitionResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public LoadReportDefinitionResponse loadReportDefinition(
        @WebParam(partName = "parameters", name = "LoadReportDefinition", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        LoadReportDefinition parameters,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ExecutionHeader", mode = WebParam.Mode.OUT, name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ExecutionHeader> executionHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "LoadReport2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReport2")
    @WebResult(name = "LoadReport2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public LoadReport2Response loadReport2(
        @WebParam(partName = "parameters", name = "LoadReport2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        LoadReport2 parameters,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ExecutionHeader", mode = WebParam.Mode.OUT, name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ExecutionHeader> executionHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "LoadDrillthroughTarget2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadDrillthroughTarget2")
    @WebResult(name = "LoadDrillthroughTarget2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public LoadDrillthroughTarget2Response loadDrillthroughTarget2(
        @WebParam(partName = "parameters", name = "LoadDrillthroughTarget2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        LoadDrillthroughTarget2 parameters,
        @WebParam(partName = "ExecutionHeader", mode = WebParam.Mode.INOUT, name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ExecutionHeader> executionHeader,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "NavigateDocumentMap", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/NavigateDocumentMap")
    @WebResult(name = "NavigateDocumentMapResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public NavigateDocumentMapResponse navigateDocumentMap(
        @WebParam(partName = "parameters", name = "NavigateDocumentMap", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        NavigateDocumentMap parameters,
        @WebParam(partName = "ExecutionHeader", name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        ExecutionHeader executionHeader,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "SetExecutionCredentials2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionCredentials2")
    @WebResult(name = "SetExecutionCredentials2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public SetExecutionCredentials2Response setExecutionCredentials2(
        @WebParam(partName = "parameters", name = "SetExecutionCredentials2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        SetExecutionCredentials2 parameters,
        @WebParam(partName = "ExecutionHeader", name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        ExecutionHeader executionHeader,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "Render", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Render")
    @WebResult(name = "RenderResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public RenderResponse render(
        @WebParam(partName = "parameters", name = "Render", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        Render parameters,
        @WebParam(partName = "ExecutionHeader", name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        ExecutionHeader executionHeader,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "GetExecutionInfo", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/GetExecutionInfo")
    @WebResult(name = "GetExecutionInfoResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public GetExecutionInfoResponse getExecutionInfo(
        @WebParam(partName = "parameters", name = "GetExecutionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        GetExecutionInfo parameters,
        @WebParam(partName = "ExecutionHeader", name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        ExecutionHeader executionHeader,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "FindString", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/FindString")
    @WebResult(name = "FindStringResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public FindStringResponse findString(
        @WebParam(partName = "parameters", name = "FindString", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        FindString parameters,
        @WebParam(partName = "ExecutionHeader", name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        ExecutionHeader executionHeader,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "LogonUser", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LogonUser")
    @WebResult(name = "LogonUserResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public LogonUserResponse logonUser(
        @WebParam(partName = "parameters", name = "LogonUser", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        LogonUser parameters,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "ToggleItem", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ToggleItem")
    @WebResult(name = "ToggleItemResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public ToggleItemResponse toggleItem(
        @WebParam(partName = "parameters", name = "ToggleItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        ToggleItem parameters,
        @WebParam(partName = "ExecutionHeader", name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        ExecutionHeader executionHeader,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "Sort", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Sort")
    @WebResult(name = "SortResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public SortResponse sort(
        @WebParam(partName = "parameters", name = "Sort", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        Sort parameters,
        @WebParam(partName = "ExecutionHeader", name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        ExecutionHeader executionHeader,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "LoadReportDefinition2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReportDefinition2")
    @WebResult(name = "LoadReportDefinition2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public LoadReportDefinition2Response loadReportDefinition2(
        @WebParam(partName = "parameters", name = "LoadReportDefinition2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        LoadReportDefinition2 parameters,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ExecutionHeader", mode = WebParam.Mode.OUT, name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ExecutionHeader> executionHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "ResetExecution", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ResetExecution")
    @WebResult(name = "ResetExecutionResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public ResetExecutionResponse resetExecution(
        @WebParam(partName = "parameters", name = "ResetExecution", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        ResetExecution parameters,
        @WebParam(partName = "ExecutionHeader", name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        ExecutionHeader executionHeader,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "SetExecutionCredentials", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionCredentials")
    @WebResult(name = "SetExecutionCredentialsResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public SetExecutionCredentialsResponse setExecutionCredentials(
        @WebParam(partName = "parameters", name = "SetExecutionCredentials", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        SetExecutionCredentials parameters,
        @WebParam(partName = "ExecutionHeader", name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        ExecutionHeader executionHeader,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "GetExecutionInfo2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/GetExecutionInfo2")
    @WebResult(name = "GetExecutionInfo2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public GetExecutionInfo2Response getExecutionInfo2(
        @WebParam(partName = "parameters", name = "GetExecutionInfo2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        GetExecutionInfo2 parameters,
        @WebParam(partName = "ExecutionHeader", name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        ExecutionHeader executionHeader,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );

    @WebMethod(operationName = "RenderStream", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/RenderStream")
    @WebResult(name = "RenderStreamResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", partName = "parameters")
    public RenderStreamResponse renderStream(
        @WebParam(partName = "parameters", name = "RenderStream", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        RenderStream parameters,
        @WebParam(partName = "ExecutionHeader", name = "ExecutionHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        ExecutionHeader executionHeader,
        @WebParam(partName = "TrustedUserHeader", name = "TrustedUserHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        TrustedUserHeader trustedUserHeader,
        @WebParam(partName = "ServerInfoHeader", mode = WebParam.Mode.OUT, name = "ServerInfoHeader", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", header = true)
        javax.xml.ws.Holder<ServerInfoHeader> serverInfoHeader
    );
}
