package com.microsoft.sqlserver.ReportService2010;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * The Reporting Services Web Service enables you to manage a report server and its contents including server settings, security, reports, subscriptions, and data sources.
 *
 * This class was generated by Apache CXF 3.0.16
 * 2018-03-11T17:35:10.224+03:00
 * Generated source version: 3.0.16
 * 
 */
@WebServiceClient(name = "ReportingService2010", 
                  wsdlLocation = "http://localhost/ReportServer/ReportService2010.asmx?wsdl",
                  targetNamespace = "http://schemas.microsoft.com/sqlserver/reporting/2010/03/01/ReportServer") 
public class ReportingService2010 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://schemas.microsoft.com/sqlserver/reporting/2010/03/01/ReportServer", "ReportingService2010");
    public final static QName ReportingService2010Soap12 = new QName("http://schemas.microsoft.com/sqlserver/reporting/2010/03/01/ReportServer", "ReportingService2010Soap12");
    public final static QName ReportingService2010Soap = new QName("http://schemas.microsoft.com/sqlserver/reporting/2010/03/01/ReportServer", "ReportingService2010Soap");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost/ReportServer/ReportService2010.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ReportingService2010.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost/ReportServer/ReportService2010.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ReportingService2010(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ReportingService2010(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReportingService2010() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ReportingService2010(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ReportingService2010(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ReportingService2010(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ReportingService2010Soap
     */
    @WebEndpoint(name = "ReportingService2010Soap12")
    public ReportingService2010Soap getReportingService2010Soap12() {
        return super.getPort(ReportingService2010Soap12, ReportingService2010Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReportingService2010Soap
     */
    @WebEndpoint(name = "ReportingService2010Soap12")
    public ReportingService2010Soap getReportingService2010Soap12(WebServiceFeature... features) {
        return super.getPort(ReportingService2010Soap12, ReportingService2010Soap.class, features);
    }
    /**
     *
     * @return
     *     returns ReportingService2010Soap
     */
    @WebEndpoint(name = "ReportingService2010Soap")
    public ReportingService2010Soap getReportingService2010Soap() {
        return super.getPort(ReportingService2010Soap, ReportingService2010Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReportingService2010Soap
     */
    @WebEndpoint(name = "ReportingService2010Soap")
    public ReportingService2010Soap getReportingService2010Soap(WebServiceFeature... features) {
        return super.getPort(ReportingService2010Soap, ReportingService2010Soap.class, features);
    }

}
